# Generated by Django 5.1.4 on 2024-12-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='lessons/'),
        ),
    ]
