# Generated by Django 5.1.4 on 2025-01-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_category_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course/thumbnail/'),
        ),
    ]
