# Generated by Django 5.1.4 on 2025-01-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_learning_outcomes_course_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
