# Generated by Django 5.1.4 on 2025-01-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_published_at_book_date_of_writing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_year',
            new_name='edition_year',
        ),
        migrations.AddField(
            model_name='book',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
