# Generated by Django 5.1.4 on 2025-01-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_course_price_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='seconds',
            field=models.IntegerField(default=0),
        ),
    ]
