# Generated by Django 5.1.4 on 2025-01-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lesson_hours_lesson_minutes_lesson_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='seconds',
            field=models.IntegerField(default=0),
        ),
    ]
