# Generated by Django 5.1.4 on 2025-01-16 12:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_course_learning_outcomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learning_outcomes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
